require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccessoryAdjustmentsController do

  # This should return the minimal set of attributes required to create a valid
  # AccessoryAdjustment. As you add validations to AccessoryAdjustment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "effective_date" => "2013-05-21" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccessoryAdjustmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all accessory_adjustments as @accessory_adjustments" do
      accessory_adjustment = AccessoryAdjustment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:accessory_adjustments).should eq([accessory_adjustment])
    end
  end

  describe "GET show" do
    it "assigns the requested accessory_adjustment as @accessory_adjustment" do
      accessory_adjustment = AccessoryAdjustment.create! valid_attributes
      get :show, {:id => accessory_adjustment.to_param}, valid_session
      assigns(:accessory_adjustment).should eq(accessory_adjustment)
    end
  end

  describe "GET new" do
    it "assigns a new accessory_adjustment as @accessory_adjustment" do
      get :new, {}, valid_session
      assigns(:accessory_adjustment).should be_a_new(AccessoryAdjustment)
    end
  end

  describe "GET edit" do
    it "assigns the requested accessory_adjustment as @accessory_adjustment" do
      accessory_adjustment = AccessoryAdjustment.create! valid_attributes
      get :edit, {:id => accessory_adjustment.to_param}, valid_session
      assigns(:accessory_adjustment).should eq(accessory_adjustment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AccessoryAdjustment" do
        expect {
          post :create, {:accessory_adjustment => valid_attributes}, valid_session
        }.to change(AccessoryAdjustment, :count).by(1)
      end

      it "assigns a newly created accessory_adjustment as @accessory_adjustment" do
        post :create, {:accessory_adjustment => valid_attributes}, valid_session
        assigns(:accessory_adjustment).should be_a(AccessoryAdjustment)
        assigns(:accessory_adjustment).should be_persisted
      end

      it "redirects to the created accessory_adjustment" do
        post :create, {:accessory_adjustment => valid_attributes}, valid_session
        response.should redirect_to(AccessoryAdjustment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accessory_adjustment as @accessory_adjustment" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccessoryAdjustment.any_instance.stub(:save).and_return(false)
        post :create, {:accessory_adjustment => { "effective_date" => "invalid value" }}, valid_session
        assigns(:accessory_adjustment).should be_a_new(AccessoryAdjustment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccessoryAdjustment.any_instance.stub(:save).and_return(false)
        post :create, {:accessory_adjustment => { "effective_date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accessory_adjustment" do
        accessory_adjustment = AccessoryAdjustment.create! valid_attributes
        # Assuming there are no other accessory_adjustments in the database, this
        # specifies that the AccessoryAdjustment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AccessoryAdjustment.any_instance.should_receive(:update_attributes).with({ "effective_date" => "2013-05-21" })
        put :update, {:id => accessory_adjustment.to_param, :accessory_adjustment => { "effective_date" => "2013-05-21" }}, valid_session
      end

      it "assigns the requested accessory_adjustment as @accessory_adjustment" do
        accessory_adjustment = AccessoryAdjustment.create! valid_attributes
        put :update, {:id => accessory_adjustment.to_param, :accessory_adjustment => valid_attributes}, valid_session
        assigns(:accessory_adjustment).should eq(accessory_adjustment)
      end

      it "redirects to the accessory_adjustment" do
        accessory_adjustment = AccessoryAdjustment.create! valid_attributes
        put :update, {:id => accessory_adjustment.to_param, :accessory_adjustment => valid_attributes}, valid_session
        response.should redirect_to(accessory_adjustment)
      end
    end

    describe "with invalid params" do
      it "assigns the accessory_adjustment as @accessory_adjustment" do
        accessory_adjustment = AccessoryAdjustment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccessoryAdjustment.any_instance.stub(:save).and_return(false)
        put :update, {:id => accessory_adjustment.to_param, :accessory_adjustment => { "effective_date" => "invalid value" }}, valid_session
        assigns(:accessory_adjustment).should eq(accessory_adjustment)
      end

      it "re-renders the 'edit' template" do
        accessory_adjustment = AccessoryAdjustment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccessoryAdjustment.any_instance.stub(:save).and_return(false)
        put :update, {:id => accessory_adjustment.to_param, :accessory_adjustment => { "effective_date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accessory_adjustment" do
      accessory_adjustment = AccessoryAdjustment.create! valid_attributes
      expect {
        delete :destroy, {:id => accessory_adjustment.to_param}, valid_session
      }.to change(AccessoryAdjustment, :count).by(-1)
    end

    it "redirects to the accessory_adjustments list" do
      accessory_adjustment = AccessoryAdjustment.create! valid_attributes
      delete :destroy, {:id => accessory_adjustment.to_param}, valid_session
      response.should redirect_to(accessory_adjustments_url)
    end
  end

end
